### ISSUE TITLE
A question on mixed-circuit computation in "Secure Quantized Training for Deep Learning"

### ISSUE THREAD

**Issue by rdeviti** [csiro-mlai/deep-mpc#13]
Hi Marcel, hope you are doing well. I have a question about the 3PC protocol in appendix A of "Secure Quantized Training for Deep Learning", which leverages mixed-circuit computation. From my understanding of the paper, whenever an ML building block (appendix C) requires comparisons, shifting and truncation (appendix A), the protocol runs domain conversion from arithmetic to binary, executes the operation, switches back to arithmetic, and proceeds. Is this correct? Does the protocol make this decision based on input parameters (e.g., the number of comparisons), or do you empirically know that it is always best to switch back and forth? Thank you!

**Comment by mkskeller** [comment]
This is correct in principle, but usually it's not the most efficient approach to plainly convert the secret value from one domain to another. See Figures 9-12 in the following paper for examples: https://eprint.iacr.org/2020/338

The selection is made empirically. For the three-party protocol in Appendix A, the cost of bit operations is so much lower than arithmetic operations that I don't have any doubts that mixed circuits perform better. Tables 7 and 8 in the paper above support this view in that the cost is considerably lower in many cases. And this is without using the local conversion used in the mentioned protocol.

**Comment by rdeviti** [comment]
Thank you for the link! Ok, so Tables 7 and 8 suggest mixed-circuit computation is better for honest-majority protocols in 2^k in both the malicious and semi-honest setting. That's really useful, thanks!

**Comment by mkskeller** [comment]
This isn't implemented completely in C++ but in a combination between the Python and the C++ code. The virtual machine (C++) provides instructions for daBits and edaBits, which are generated in the following two places for 3PC protocol mentioned above (but other places for other protocols):
- https://github.com/data61/MP-SPDZ/blob/3b166ca2d7bd7083ca8b9f50100fe02970e50042/Protocols/ReplicatedPrep.hpp#L726
- https://github.com/data61/MP-SPDZ/blob/3b166ca2d7bd7083ca8b9f50100fe02970e50042/Protocols/ReplicatedPrep.hpp#L962

The high-level code uses daBits and edaBits for conversions calling further instructions.

**Comment by rdeviti** [comment]
Thank you!
