### ISSUE TITLE
Running on Ubuntu withou docker

### ISSUE THREAD

**Issue by llCurious** [csiro-mlai/deep-mpc#5]
Hey @mkskeller . I intend to run a benchmark on Ubuntu and  i wonder is there a install script so that i can run the experiments on my Ubuntu with the same environment, instead build with Docker?

**Comment by llCurious** [comment]
Just walk through by runing each command in Dockerfile.

BTW, how could i modify the code to use 64-bit rather 128-bit computation?

**Comment by mkskeller** [comment]
If you increase the precision to 32, the underlying domain should automatically be changed to 128 bits to fit it.

**Comment by llCurious** [comment]
Yep，i try to use precision of 16 and it seems that the domain is converted to 2^64. Maybe you could have a look at on my experiment figures? I run the Network-A (SecureML) for 2 epochs and obtain the following statistics.
![image](https://user-images.githubusercontent.com/21785695/179165735-ae329838-43de-452d-bc85-6abecb1a8f34.png)

**Comment by llCurious** [comment]
The figures seems to be much slower than the figure in the paper https://arxiv.org/pdf/2107.00501.pdf

**Comment by mkskeller** [comment]
- The domain needs to be four times as large as the fixed-point precision.
- The figures in the paper have been obtained with 36 threads on c5.9xlarge instances.

**Comment by llCurious** [comment]
Got it.
- I set the precision to 16, which is exactly 1/4 of 64. This validate that my parameter is correctly configured? With 64-bit FXP and precision of 16.
- I recon that suppose the experiment environment is the same, the comparison shall be fair. And maybe the performance of my Ubuntu server is poor QAQ. BTW,  is the multi-thread a significant optimization in MP-SPDZ? I wonder maybe i should use thread=2 here for a more fair comparison?

**Comment by mkskeller** [comment]
- 16 fixed-point precision, 64-bit domain is the default.
- If more cores are available, using more threads should be more efficient, but I haven't looked into this.

**Comment by llCurious** [comment]
hey @mkskeller . Wanna check one point: is the time counted for online or online+offline? Since i noticed that the output has "The following timing is inclusive preprocessing"?

**Comment by mkskeller** [comment]
The time is online+offline if it says "inclusive".
